apiVersion: v1
kind: Secret
metadata:
  name: bigdata-secrets
  namespace: bigdata
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow123
  POSTGRES_DB: airflow
  AIRFLOW_FERNET_KEY: 46gZFTnvQuRz668eqxUJAawawBFSpQU6P92GHnGDu8w=
  AIRFLOW_WEBSERVER_SECRET_KEY: 82f9d6c382104bf7b4a2e5a61d8f1e2c
