apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: bigdata
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
    - name: rpc
      port: 7077
      targetPort: rpc
    - name: driver
      port: 7078
      targetPort: 7078
    - name: blockmanager-1
      port: 7079
      targetPort: 7079
    - name: blockmanager-2
      port: 7080
      targetPort: 7080
    - name: blockmanager-3
      port: 7081
      targetPort: 7081
    - name: blockmanager-4
      port: 7082
      targetPort: 7082
    - name: blockmanager-5
      port: 7083
      targetPort: 7083
    - name: ui
      port: 8080
      targetPort: ui
      nodePort: 32081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role
                    operator: In
                    values: [master]
      containers:
        - name: spark-master
          image: bde2020/spark-master:3.3.0-hadoop3.3
          env:
            - name: INIT_DAEMON_STEP
              value: setup_spark
            - name: SPARK_MASTER_HOST
              value: 0.0.0.0
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
          ports:
            - name: rpc
              containerPort: 7077
            - name: ui
              containerPort: 8080
