apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-spark-defaults
  namespace: bigdata
data:
  spark-defaults.conf: |
    spark.executor.memory 2g
    spark.executor.cores 4
    spark.executor.memoryOverhead 512m
    spark.driver.memory 2g
    spark.driver.bindAddress 0.0.0.0
    spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.endpoint http://minio.bigdata.svc.cluster.local:9000
    spark.hadoop.fs.s3a.path.style.access true
    spark.hadoop.fs.s3a.connection.ssl.enabled false
    spark.hadoop.fs.s3a.aws.credentials.provider com.amazonaws.auth.EnvironmentVariableCredentialsProvider
    spark.files.io.connectionTimeout 600s
