# S3A/MinIO defaults. Credentials come from Kubernetes environment variables.
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint http://minio.bigdata.svc.cluster.local:9000
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.aws.credentials.provider com.amazonaws.auth.EnvironmentVariableCredentialsProvider
spark.jars /opt/conda-repaired/lib/python3.10/site-packages/pyspark/jars/hadoop-aws-3.3.2.jar,/opt/conda-repaired/lib/python3.10/site-packages/pyspark/jars/aws-java-sdk-bundle-1.11.1026.jar
spark.files.io.connectionTimeout 600s
